# Generated by Django 3.2.5 on 2021-07-23 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandsFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('price', models.PositiveBigIntegerField()),
                ('year', models.CharField(max_length=4)),
                ('Type', models.CharField(max_length=50)),
                ('sound_quality', models.IntegerField(choices=[(1, 'Bad'), (2, 'Medium'), (3, 'Good')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_price', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('price', models.PositiveBigIntegerField()),
                ('year', models.CharField(max_length=4)),
                ('screen', models.CharField(max_length=50)),
                ('cpu', models.CharField(max_length=50)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='item.seller')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
